<?php
/**
 * Template Name: Home Page Alt
 *
 * @package Student Design Collective
 */

get_header(); ?>

<div class="jumbotron">
  <div class="jumbotron-overlay">
  	<div class="hero-unit">
    	<h1>SDC makes connecting with other MCTC design students easy</h1>
    	<p>Get critiques of your work, hear guest speakers on the creative proccess, and build your resume and portfolio. Connection counts. </p>
    </div>
  </div>
</div>

<div class="container">
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum dictum rutrum lorem non euismod. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet faucibus mi. Donec lorem lacus, rhoncus sed ipsum a, malesuada euismod nibh. Morbi augue massa, sollicitudin eu dictum nec, gravida nec libero. Nam blandit tristique odio, ut semper dolor viverra eget. Quisque sodales velit eu dolor adipiscing luctus.

Donec condimentum massa dolor, in lacinia lorem malesuada non. Vestibulum interdum sed justo sed iaculis. Pellentesque tincidunt libero mauris, sed molestie sapien accumsan et. Nam ac nisi a lorem suscipit egestas ut sit amet nulla. Mauris cursus tincidunt lacus id sollicitudin. In hac habitasse platea dictumst. Donec ac mattis risus, at interdum neque. Vestibulum at molestie nulla, in dictum diam. Suspendisse dui tellus, vestibulum eget felis ac, porta mollis nisi. Ut interdum in mauris at egestas. Aliquam sodales purus ut quam viverra, vitae tincidunt velit pulvinar.

Nam posuere urna ut ipsum viverra vulputate. Nam quis urna non enim interdum volutpat sed non ligula. Nullam dapibus, neque eu consequat egestas, odio libero posuere eros, sed congue felis ligula vitae odio. Vivamus consequat convallis est, quis luctus risus suscipit non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras eros sapien, vulputate ac sagittis in, convallis ultricies magna. Donec tellus turpis, scelerisque eget elit ut, tincidunt porttitor arcu. Cras dui mi, pulvinar a ante vitae, ullamcorper convallis leo. Mauris vestibulum eget nunc non fringilla. Nam laoreet dictum est, eu viverra ligula gravida ac. Mauris sagittis et nisi sed tristique. Cras at sodales ligula, ac vestibulum mi. Aliquam pulvinar gravida quam sed molestie. Nullam malesuada massa magna, iaculis laoreet lacus iaculis eu.

Ut et lectus quis urna euismod tristique. Phasellus sed diam id enim pulvinar lacinia vel ac tellus. Donec id dui tortor. Donec eu ligula id mauris lacinia consectetur at elementum tellus. Aliquam ut malesuada est, non mattis lacus. Nam condimentum erat leo, et dignissim lacus varius quis. Nullam euismod nibh turpis, nec pulvinar odio lobortis in. Aliquam vel venenatis nisi. Nullam ut lacus sed dolor accumsan facilisis vitae in leo. Phasellus accumsan enim lacus, at iaculis arcu feugiat vitae. Duis lacus purus, tincidunt vel tincidunt vitae, bibendum at magna. Integer et neque erat. Etiam eget est vitae urna molestie tincidunt. Nunc ligula elit, varius sed eros vitae, mollis venenatis erat.

Vivamus justo tellus, porttitor a felis sit amet, interdum malesuada ligula. Ut egestas augue dui, et malesuada elit ornare et. Nunc sagittis auctor varius. Donec interdum mi eu nisi ultrices, vitae pellentesque nisl rutrum. Pellentesque ultrices dui at sem laoreet gravida. Duis adipiscing molestie ipsum at tincidunt. Pellentesque nec ante in sem ultrices faucibus vitae eu nulla. Etiam in blandit turpis. Aliquam mattis placerat nisi, ac luctus nulla tincidunt quis.

Morbi eu auctor risus. Duis imperdiet in purus malesuada hendrerit. Donec semper neque nisi, non pellentesque nibh pretium eu. Proin in felis id sem lacinia vehicula vel eget lacus. In felis augue, vestibulum non lacus viverra, sagittis ornare massa. Nam velit ipsum, rutrum id mollis pharetra, scelerisque non turpis. Praesent non magna quam. Fusce in odio sodales, bibendum est sit amet, lacinia dolor. Vestibulum elementum tincidunt ante, vitae venenatis nibh gravida egestas. Pellentesque at velit lectus. Maecenas nec magna sed quam sollicitudin convallis et sit amet nibh. Nulla ullamcorper vulputate lacinia. Integer vel arcu condimentum, blandit risus quis, euismod leo. Nulla sollicitudin posuere quam in auctor. Vivamus rhoncus volutpat lacus sed tincidunt. Suspendisse elementum sodales blandit.

Nulla vehicula arcu eget nulla iaculis sodales laoreet sit amet nisi. Curabitur tristique nunc velit. Donec interdum urna et justo blandit lacinia. Vivamus augue nisi, faucibus sodales ligula ullamcorper, laoreet ultricies ipsum. Vestibulum libero eros, dapibus ut felis ut, elementum feugiat erat. Praesent consequat elit et odio pharetra pulvinar. Sed adipiscing egestas est a tempor. Donec sit amet magna sed tortor placerat placerat. Suspendisse commodo justo velit, a adipiscing sem auctor auctor. Sed hendrerit porttitor ullamcorper. Praesent sollicitudin ut tortor non placerat. Maecenas a nisi semper, blandit turpis eget, iaculis eros. Curabitur tortor arcu, eleifend sit amet nisi at, viverra interdum mi. Duis odio tortor, semper eu egestas quis, porta tincidunt risus. Integer mattis elit posuere libero vehicula bibendum.

Etiam fermentum tellus sit amet tincidunt malesuada. Nunc suscipit justo enim, blandit facilisis nunc vulputate at. Donec rhoncus dapibus diam. Pellentesque non turpis metus. Aliquam erat volutpat. Morbi at lectus non ante ultricies tempor. Sed iaculis odio vitae ipsum consequat rutrum.

Aenean congue elit eget rutrum vestibulum. Phasellus sed mi odio. Mauris cursus risus sed nunc egestas rutrum. Quisque justo enim, volutpat sit amet nibh vitae, adipiscing vehicula elit. Cras nisi leo, porttitor id bibendum sed, tincidunt et quam. Nam interdum nisl in lectus egestas ullamcorper. Cras porta lacus purus, sed tincidunt nulla congue eu. Pellentesque dapibus est in ultricies tempor.

Pellentesque dictum imperdiet turpis in dignissim. Cras et lorem dignissim, rhoncus ligula vel, consequat metus. Morbi nulla diam, ullamcorper sit amet vehicula id, vestibulum nec quam. Nam a neque sit amet diam ullamcorper sagittis vel in lorem. Suspendisse vestibulum porttitor venenatis. Nunc lobortis at elit quis ultrices. Sed bibendum adipiscing risus, eu mattis libero ornare sit amet. Donec lacinia ante justo, eu feugiat velit mollis porttitor. Nam sem diam, imperdiet congue purus non, fermentum mattis tortor. Nunc lacinia aliquet semper. Pellentesque non fringilla justo. Nulla a nibh id magna gravida volutpat. Quisque eget elit quis urna tincidunt feugiat et sed lectus. Etiam sit amet augue ac diam mollis facilisis non vel purus.

Mauris mollis arcu dui, ut porta est sollicitudin ut. Phasellus dignissim venenatis ultrices. Nam suscipit, est a mollis sodales, quam odio ultricies justo, pulvinar suscipit libero sem sit amet tellus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent suscipit semper aliquam. Mauris vestibulum consequat augue quis viverra. Nullam id faucibus nisi. Sed nec nisl eleifend, interdum magna sit amet, facilisis mi. Donec sollicitudin neque non auctor convallis. Mauris mauris arcu, convallis egestas massa vitae, auctor lobortis eros. Mauris vitae euismod felis. Morbi et viverra massa. Donec pellentesque dignissim magna ac porta. Aenean placerat viverra dapibus. Sed consequat arcu massa, eu iaculis ante egestas sit amet. Aliquam vehicula, nisl pretium hendrerit accumsan, nisi elit viverra mi, ut ultricies magna ante et lorem.

Fusce eget nulla quis ligula malesuada euismod. Duis in ullamcorper urna, ac sollicitudin massa. Phasellus erat elit, cursus sit amet ligula quis, consectetur volutpat orci. Fusce aliquam in nulla eu sagittis. Nam sed sodales arcu. Nullam malesuada malesuada laoreet. Cras varius urna sed turpis pretium, sed lobortis eros accumsan. Mauris sem orci, adipiscing porttitor iaculis vel, laoreet quis libero. Vivamus vel vulputate diam. Pellentesque ultricies quam porttitor, consequat velit a, tristique neque.

Vivamus vitae iaculis augue, eget condimentum est. Sed sem nulla, consequat nec lectus nec, rutrum commodo nulla. Vestibulum in mi eget lorem viverra suscipit mattis sed lacus. Mauris pulvinar tristique pulvinar. Morbi non tellus risus. Sed semper rhoncus condimentum. Pellentesque tempor ipsum at pretium mattis. Sed eget elit accumsan, blandit magna sed, consectetur erat. Nunc velit est, rhoncus nec velit id, aliquam interdum leo. Praesent quis ultricies enim. Nunc rhoncus eget urna vel congue. Nunc semper porta nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a ullamcorper sem. Pellentesque tempus varius tortor ut rhoncus. Pellentesque erat magna, dapibus vel placerat sit amet, molestie sed tortor.

Donec pretium odio velit, ac malesuada quam sollicitudin sit amet. Morbi a metus nibh. Pellentesque vel sollicitudin tortor, quis euismod massa. Sed eget risus nulla. Nunc dapibus lectus nisi, sit amet pharetra mi faucibus nec. Fusce sollicitudin mauris tincidunt, fringilla metus eget, consectetur augue. Morbi eu porta felis, sed dictum eros.

Suspendisse non ipsum ac ligula laoreet pharetra sed in leo. Praesent posuere interdum tortor eu ullamcorper. Duis vulputate massa sed justo aliquam, ac lobortis leo dignissim. Proin accumsan cursus rhoncus. Sed non pulvinar sem. Nunc accumsan dolor nec feugiat suscipit. Aenean sit amet nibh eros. Proin elementum tellus quis erat commodo porttitor.

Sed sem tortor, tincidunt eu dapibus eleifend, faucibus et risus. Cras quis elit lacus. Mauris ante dolor, aliquam et lacus at, mattis suscipit augue. Donec semper dui malesuada lacus gravida, nec pretium sapien porta. Pellentesque dignissim convallis sem, eu pharetra lectus feugiat scelerisque. Sed accumsan justo quis lorem suscipit, sed consectetur ipsum convallis. Integer cursus urna id lorem sollicitudin vestibulum vel ut massa. Cras blandit turpis nec purus commodo, vel cursus massa facilisis. Suspendisse rutrum massa nec lacinia aliquet. Pellentesque pharetra lobortis odio, et placerat sem rhoncus in. Duis id dapibus nunc, sit amet ornare turpis. Sed id libero quis eros blandit porta at quis nulla. Vivamus tortor ipsum, fringilla eu tristique ac, fermentum quis libero. Nunc quis lacinia eros. In porttitor risus dui, ac commodo mi posuere quis. Donec dapibus, nunc vel euismod fermentum, massa nibh rhoncus tellus, nec cursus nibh augue eget ipsum.

Praesent consectetur turpis id mi vehicula laoreet. Nullam ultrices at justo eu porttitor. Quisque pretium metus sed venenatis elementum. Mauris condimentum tincidunt adipiscing. Proin in tempus justo, nec sodales odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ante velit, pretium ultricies sem sit amet, gravida imperdiet tortor. Cras bibendum, sapien id ultricies tincidunt, justo mauris ullamcorper risus, a adipiscing lacus diam in justo.

Mauris posuere vehicula enim et convallis. Etiam mollis commodo elit a fermentum. Donec dolor lacus, suscipit ut consequat eget, fermentum semper ligula. Ut mollis odio at augue pretium suscipit. Fusce laoreet feugiat rhoncus. Nam porttitor magna vitae aliquam vestibulum. Fusce volutpat tincidunt sapien et sodales. Donec aliquet nec libero eget luctus. Duis vehicula fringilla rhoncus. Proin ultricies sed felis nec blandit.

Quisque consequat dapibus risus quis consequat. Mauris tellus est, convallis quis erat eget, porta cursus tortor. Nunc ultricies, nulla at scelerisque scelerisque, enim nisl convallis urna, non varius lorem nisi at est. Suspendisse massa orci, gravida nec massa eget, tempus faucibus ante. Curabitur convallis et justo non pulvinar. Nullam massa libero, posuere ac viverra a, dignissim at massa. Etiam eu odio suscipit, condimentum dui sodales, interdum urna. Etiam ut diam ante. Mauris vitae tortor sit amet ligula ornare ultricies eu hendrerit mi. Maecenas quis feugiat nibh. Cras at congue felis, vel tincidunt purus. Pellentesque elementum tempus lorem euismod tempus. Duis varius quis neque at egestas. Morbi tristique bibendum aliquam. Pellentesque elementum libero vel porttitor mollis.

Nam interdum lobortis urna non hendrerit. Etiam lacus dolor, blandit et enim sollicitudin, cursus feugiat nulla. Etiam vulputate fringilla lectus nec gravida. Integer cursus, lectus at viverra tincidunt, massa odio blandit orci, at laoreet arcu lectus eget purus. Mauris porttitor justo vel lacus consectetur, a pellentesque nisi fermentum. Nulla tempor sed risus vitae pellentesque. Duis justo nulla, blandit sed sagittis nec, malesuada non arcu.
</div>

<?php get_footer(); ?>
